author: blueMix
description: Ù…Ø¯ÙˆÙ†Ø© Ø¹Ø¨Ø¯ Ø§Ù„Ù…Ø¤Ù…Ù†
keywords: hexo-theme, rexo, rtl, multilingual

theme_name: Rexo
theme_url: https://github.com/bluemix/hexo-theme-rexo

menu:
#  ğŸ : /
#  ğŸ·: /tags/
#  ğŸ“—: /archives/
 ğŸ“Ÿ: /projects/
#  ğŸ“™: /cv/
#  ğŸ: /photography/
 ğŸ‘¨ğŸ»â€ğŸ’»: /about/

# highlight
highlight:
  tomorrow

# Comment
comment:
    disqus: bluemixme


google_analytics: UA-104099189-1

about: 
  avatar: https://avatars3.githubusercontent.com/u/3332274?v=4&s=460
  description: Peace  â˜®ï¸  Ø§Ù„Ø³Ù„Ø§Ù… 
  long_description:
social:
  github: https://github.com/bluemix
  github_username: bluemix
  stackoverflow: https://stackoverflow.com/users/1150190/abdulmomen-Ø¹Ø¨Ø¯Ø§Ù„Ù…Ø¤Ù…Ù†
  twitter: https://twitter.com/bluemix2
  facebook: https://fb.com/bluemix
  linkedin: https://www.linkedin.com/in/bluemix2
  instagram: https://instagram.com/bluemix

# Customize
customize:
    sidebar: right # sidebar position, options: left, right or leave it empty

miscellaneous:
    links:
      - link:
        - Archive | Ø§Ù„Ø£Ø±Ø´ÙŠÙ
        - /archives/
        - ğŸ“—
      - link: 
        - Quotes | Ø­ÙƒÙ…
        - /quotes/
        - ğŸ“
      - link: 
        - Songs & Music | Ù…ÙˆØ³ÙŠÙ‚Ù‰ Ùˆ Ø£ØºØ§Ù†ÙŠ
        - /music
        - ğŸµ
      - link: 
        - Inspired by | Ø£Ø´Ø®Ø§Øµ Ø£Ø­Ø¨Ù‡Ù…
        - /inspired
        - ğŸ’–


